---
install:
   - linux-image-extra-virtual
   - htop
   - multitail
   - build-essential
   - software-properties-common
   - python-software-properties
   - curl
   - bridge-utils
   - git
   - lldpd
   - lsof
   - ntp
   - ntpdate
   - ssh
   - sudo
   - tcpdump
   - vim
   - vlan
   - ifenslave
   - python-apt
   - python-dev
   - tmux
   - libffi-dev
   - libssl-dev
   - lvm2
   - fping
   - openssh-server
