---
# This playbook installs Rackspace Private Cloud v13.1

- name: Do Nothing
  hosts: all
  tags:
    - prepare
  tasks:
    - name: Ping Nodes
      ping:

- name: Prepare Environment
  hosts: all
  tags:
    - prepare
  roles:
    - packages

- name: Setup Cinder Volume Groups
  hosts: block
  tags:
    - prepare
  roles:
    - volumes

- name: Reboot Cluster
  hosts: all:!deployment
  tags:
    - reboot
  roles:
    - reboot
