---
# RPC-on-RPC Host Setup Playbook
- name: Install Packages
  hosts: all
  tags:
    - prepare
    - packages
  roles:
    - packages

- name: Setup Host Files
  hosts: all
  tags:
    - prepare
    - hosts
  roles:
    - hosts

- name: Setup Cinder Volume Groups
  hosts: block
  tags:
    - prepare
    - volumes
  roles:
    - volumes

- name: Setup Swift Mount Points
  hosts: object
  tags:
    - prepare
    - mounts
  roles:
    - mounts

- name: Setup Networking
  hosts: all
  tags:
    - prepare
    - networking
  roles:
    - networking

- name: Setup Rackspace Private Cloud Configuration
  hosts: deployment
  tags:
    - prepare
    - configure-rpc
  roles:
    - configure-rpc
